version: '2.3'
services:
  mysql:
    build: ./mysql
    container_name: general_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "127.0.0.1:3303:3306"
    networks:
      - network
    volumes:
      - ./mysql/conf/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - ${MYSQL_DUMP}:/docker-entrypoint-initdb.d/dump.sql
      - ./mysql/log:/var/log/mysql
      - ./mysql/SAVE/${BRANCH_NAME}:/var/lib/mysql
    labels:
      - "traefik.enable=false"
  # OPTIONALS (add them in the SERVICES var in the .env file):
  # eg: SERVICES=django... redis cerebro
  portainer:
    image: "portainer/portainer"
    container_name: prototype_portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:9003:9000"
    networks:
      - network
    labels:
      - "traefik.enable=false"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    container_name: general_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    privileged: true
    volumes:
      - /sessions
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "127.0.0.1:8083:80"
    networks:
      - network
    labels:
      - "traefik.enable=false"
    depends_on:
      - mysql
networks:
  network:
      name: general_network
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 192.1.3.0/24
          gateway: 192.1.3.1
