<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.11.1deb1 setup script
 * Date: Mon, 17 Dec 2012 15:13:56 +0100
 * sudo vim /var/lib/phpmyadmin/config.inc.php
 */

/* Servers configuration */

$i = 0;

$i++;
$cfg['Servers'][$i]['verbose'] = 'general';
$cfg['Servers'][$i]['host'] = 'general_mysql';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'password';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'cA=S}{Pj;gOIDQ8e=hYxvWVDWGDpzBMZ';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LoginCookieValidity'] = 43200;  // 12 hours
?>
